options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _AR_HOSTNAME: asia-east1-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  _DEPLOY_REGION: asia-east1
  _PLATFORM: managed
  _SERVICE_NAME: civictech-vpass

steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --no-cache
      - -t
      - $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - -f
      - Dockerfile
      - .

  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA

  - id: Decrypt secrets
    name: ghcr.io/getsops/sops:v3.8.1
    entrypoint: sh
    args:
      - -c
      - |
        sops --decrypt --input-type dotenv --output-type dotenv secrets/prod.env.enc > secrets/.prod.env

  - id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy $_SERVICE_NAME \
          --project=$PROJECT_ID \
          --region=$_DEPLOY_REGION \
          --platform=$_PLATFORM \
          --allow-unauthenticated \
          --add-cloudsql-instances=$PROJECT_ID:$_DEPLOY_REGION:vpass-db \
          --image=$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA \
          --env-vars-file=secrets/.prod.env

images:
  - $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
